name: Setup Nix with Cachix
description: Install Nix and configure Cachix
inputs:
  cachix_auth_token:
    description: Authentication token for Cachix, required for private cache access or to push to any cache
    required: false
runs:
  using: composite
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v31
    - name: Configure Cachix
      uses: cachix/cachix-action@v16
      with:
        name: redirector
        authToken: ${{ inputs.cachix_auth_token }}
