name: Check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Nix
        uses: ./.github/actions/setup-nix
      - name: Run pre-commit Check
        run: nix build .#checks.x86_64-linux.pre-commit -v -L
      - name: Run Build Check
        run: nix build .#redirector -v -L
      - name: Run home-module Check
        run: nix build .#checks.x86_64-linux.home-module -v -L
